experiment:
    algorithms:
        random:
            seed: 999


    max_broken: 4096
    max_trials: 4096
    working_dir: /tmp/solo-orion_asdfasfasgafasdfa

evc:
  enable: False

worker:
   pool_size: 32
   reservation_timeout: 360
