experiment:
    algorithms:
        # asha:
        #     seed: 999
        #     repetitions: 1
        #     num_rungs: 3
        #     num_brackets: 1
        random:
          seed: 999


    max_broken: 4096
    max_trials: 4096
    working_dir: /tmp/solo-orion_asdfasfasgafasdfa

evc:
  enable: False

worker:
   pool_size: 32
   reservation_timeout: 360
